### ISSUE TITLE
Contributor docs content

### ISSUE THREAD

**Issue by limzykenneth** [bocoup/p5.js-website#121]
The updated and translated contributor docs are currently in the p5.js repo [here](https://github.com/processing/p5.js/tree/main/contributor_docs) and I believe the idea is to pull the data from there on build or similar. Is this currently in the works and/or can the contributor docs content at least be updated before the content freeze on April 10 so we have the latest version?

**Comment by outofambit** [comment]
@limzykenneth i can make sure these get in before end of thursday at the latest. would you mind taking a quick look that the changes in #123 in `src/content/` match what you'd expect to get updated? it looks like perhaps a number of docs were removed in this last set of revisions?

**Comment by limzykenneth** [comment]
A quick look at #123 seems good to me. There are a number of docs that are consolidated or archived so they no longer exist on their own. For the most part as long as the script to pull and build the contributor docs from latest on the p5.js repo is functional I can take care of getting it up to date (eg. there are a couple more smaller translations we still need to complete).

**Comment by outofambit** [comment]
sounds great @limzykenneth ! yes, after this PR merges you should be able to use it whenever to pull in the latest. its `npm run build:contribute`
