### ISSUE TITLE
UI and website copy for translation

### ISSUE THREAD

**Issue by Qianqianye** [bocoup/p5.js-website#128]
While we are preparing for the UI and website copy for translation, we noticed that there are a few items missing or need updates in the [ui/en.yaml](https://github.com/bocoup/p5.js-website/blob/main/src/content/ui/en.yaml). It seems like all the changes in this [commit](https://github.com/bocoup/p5.js-website/commit/242730ca075135bb3cc06abdd6732b620a738bbe) are not there.

**Filter by keyword**
We will need to add 'Filter by keyword'.

**Page names:**
In the 'briefPageDescriptions' section of [ui/en.yaml](https://github.com/bocoup/p5.js-website/blob/main/src/content/ui/en.yaml), we will need to remove the word 'Archive'.

**Community page:**
We won't have 'Core Libraries' and 'Community Libraries' in the community page, we will just call it 'Libraries'.

**Accessibility setting:**
We understand that we might not implement 'Reduced Motion' in this round, but we'd like to add it in the UI list and have it translated since we'd like to include it for future implementation.

Please let us know how you'd like to proceed. I can open a PR if it's easier. Thanks!

@stalgiag @outofambit; cc @limzykenneth @davepagurek

**Comment by stalgiag** [comment]
Thanks for flagging!

I won't be able to get to this today so if this is a prerequisite for your work feel free to open a PR (and even merge directly once tests pass). Your team probably has the best sense of the needed UI text. Otherwise, I can add these key-value pairs at the beginning of next week.

**Comment by Qianqianye** [comment]
Resolved with PR #129
