### ISSUE TITLE
Styling issues in Home / Navigation Bar / side bar / footer

### ISSUE THREAD

**Issue by ccanash** [bocoup/p5.js-website#193]
This issue will track the styling issues in the[ staging site](https://p5js-wip.online/) for Home / Navigation Bar / side bar. Please add any additional items you might find during testing to this issue.

**DESKTOP 1280 x 800**

1. Top image: 
- [x] The first image is supposed to cover all of the space from left to right. There is a small space of white to the right when you scroll.   
- [x] There should be a black line above and below the image 

2. Home content:
- [x] The buttons for each section (Reference, Example, etc) have a black border that is bold, the line for them should be thinner. 
- [x] The images are a square shape instead of rectangle 
- [x] The Donate text at the bottom of the page should be 56 px, it is currently 40px. Same for Download p5.js
- [x] The Donate button should be widder. 
- [x] New: the images should should alternate left - right - left- right. They are currently all to the right. 

3. Footer:  
- [x] The asterisk should start at the height of the  donate text. It starts now below donate. 
- [x] The text should be 20px, it is 18px. 

**TABLET 768 x 800**
1. Header section:
- [x] Reduce spacing between top menu and the start of the text. 
- [x] Reduce spacing between the top text and the description of the first image ‘ Lauren Lee… ‘

2. Navigation:
- [x] Search text is not well centered from top to bottom
- [x] The symbols (magnifying glass, world, setting) for the navigation items in pink are not well centered from top to bottom.  

3. Home content:
- [x] The buttons for each section (Reference, Example, etc) have the text overflow the limits of the button 
- [x] The sections of Explore the p5.js library reference and Learn p5.ks with examples shouldn’t have image previews.
- [x]  The Donate text at the bottom of the page should be 56 px, it is currently 40px. Same for Download p5.js
- [x] Images should be rectangles not squares 
- [x] The Donate button should be widder. 
- [x] **New:** the main image should be taller from top to bottom.

4. Footer
- [x] - [ ] There should only be 3 columns in the footer. Socials should be below Information per figma

**Mobile 428x800** 
1. Navigation:
- [x] Search should be at the top, above English and Accessibility

2. Home content:
- [x] Images should be rectangles not squares 
- [x] At the bottom, the Download Library button should be displayed in one line, not two.

**Comment by ccanash** [comment]
Posting updated status of issues plus new items identified during second round of testing:

**DESKTOP**

1. Home content:
- [ ] **New:** the images should should alternate left - right - left- right. They are currently all to the right. 

2. Footer:  
- [ ] The asterisk should start at the height of the  donate text. It starts now below donate. 

**TABLET 768 x 800**

1. Home content:
- [ ] **New:** the main image should be taller from top to bottom.

**Mobile 428x800** 
1. Navigation:
- [ ] Search should be at the top, above English and Accessibility

2. Home content:
- [ ] At the bottom, the Download Library button should be displayed in one line, not two.  **This is a reopened item.**

**Comment by davepagurek** [comment]
In the sidebar on a tutorial page (e.g. https://p5js-wip.online/tutorials/setting-up-your-environment/), the category name is not capitalized (maybe using the slug version rather than the full name?) Here, it says "introduction" rather than "Introduction to p5.js":

![image](https://github.com/bocoup/p5.js-website/assets/5315059/454a016e-b5f3-41f2-88f9-aff59c2aa5d9)

**Comment by davepagurek** [comment]
Also seems like the bottom left area is scrollable even though it is sized to match the content:

![scroll-area](https://github.com/bocoup/p5.js-website/assets/5315059/5a961b41-eb17-4a88-a9f3-68fb77023729)

**Comment by limzykenneth** [comment]
I'm seeing the sidebar usually not scrolling to the bottom:

<img width="481" alt="Screenshot 2024-04-16 at 12 08 07" src="https://github.com/bocoup/p5.js-website/assets/7543950/e6c023d4-a63d-4bd1-8539-513df3ebbe55">

**Comment by ccanash** [comment]
- [ ] Sidebar. In tablet, the references title remains visible when menu is closed 
![Screenshot 2024-04-24 at 16 06 05](https://github.com/bocoup/p5.js-website/assets/36164089/d53a5fee-8155-4be3-a790-9d1faa13920e)

**Comment by ccanash** [comment]
Closing as all items have been retested and addressed
