### ISSUE TITLE
Missing list formatting

### ISSUE THREAD

**Issue by davepagurek** [bocoup/p5.js-website#203]
Hi! Looks like tutorials that use lists currently don't show any indentation or bullets, e.g.: https://p5js-wip.online/tutorials/color-gradients/

<img width="1359" alt="image" src="https://github.com/bocoup/p5.js-website/assets/5315059/6d200d33-62aa-4276-b0ea-3eb16d03c5e9">

**Comment by stalgiag** [comment]
Was addressed by #218
