### ISSUE TITLE
Tutorials page currently lists everything vertically

### ISSUE THREAD

**Issue by davepagurek** [bocoup/p5.js-website#206]
These probably should use the horizontal space a bit:

![image](https://github.com/bocoup/p5.js-website/assets/5315059/bf7baed1-e769-4d88-90f3-335764607141)

**Comment by stalgiag** [comment]
Tutorials page hasn't been worked on yet. Not sure if you received the delivery email but these routes are to-be-completed

The following items will be implemented before launch:

- Tutorials
- People
- About
- Contact us 
- Donate
- Access
- Code of Conduct
- Copyright
- Download
- Privacy Policy
- Terms of Use
- Non-english languages 
- Address pending QA

**Comment by davepagurek** [comment]
Ah makes sense, sorry for the extra noise!

**Comment by ccanash** [comment]
Closing as invalid
