### ISSUE TITLE
Tutorial page formatting QA

### ISSUE THREAD

**Issue by davepagurek** [bocoup/p5.js-website#208]
- [ ] Related references/examples showing up as `[object object]`:
       ![image](https://github.com/bocoup/p5.js-website/assets/5315059/691c4055-3864-4b08-9e6d-4cf35ea6baf2)
- [ ] Related references/examples headers still showing up even if the section is empty
- [ ] Links appear the same as body text before hovering:
      ![link-underline](https://github.com/bocoup/p5.js-website/assets/5315059/ea67a8fc-790a-49e7-a24a-965826c63a81)
- [ ] Images are currently allowed to be much larger than the height of the screen, e.g. the first image in https://p5js-wip.online/tutorials/repeating-with-loops/ Is there an across-the-board way to get more reasonable image sizing for images embedded using the default markdown image syntax, or do we have to convert those to `<Image>` components to specify a size?
- [ ] The text width for tutorials is the full width of the screen when the screen is large, which gets rather hard to read. For the reference page, there is a margin added on the right when the screen gets wide. Would it make sense to match the reference page, or  maybe use a reasonable max text width for both?

**Comment by stalgiag** [comment]
See [this comment](https://github.com/bocoup/p5.js-website/issues/206#issuecomment-2059555318)

**Comment by ccanash** [comment]
Closing this as invalid as we haven't started working on tutorial yet.
