### ISSUE TITLE
Potential 1.9.3 release this week

### ISSUE THREAD

**Issue by Qianqianye** [bocoup/p5.js-website#220]
We updated the last round of reference to include one-line description and merged the last PR today. We'd like to do a patch release `1.9.3` on this Tuesday or Wednesday, but we want to double check with you first to see if it's feasible. Thanks! @stalgiag @outofambit 

CC @limzykenneth @davepagurek

**Comment by Qianqianye** [comment]
That's great to hear. All of the one-line description is the first sentence for each reference item. We are only aiming to update the main reference description, so we can finish translate most reference items. 
The JSDoc switch will happen later @limzykenneth @davepagurek

**Comment by Qianqianye** [comment]
We just released [1.9.3](https://github.com/processing/p5.js/releases/tag/v1.9.3), could you update the reference on the new website? Thanks!

**Comment by stalgiag** [comment]
The reference has been updated with #237 . It should be reflected on the staging website in about 15 or so minutes (once the Github Pages build finishes).
