### ISSUE TITLE
Styling issues identified in translations

### ISSUE THREAD

**Issue by ccanash** [bocoup/p5.js-website#223]
- [x] In the dropdown menu for Languages, the languages that use the latin alphabet should start with a caps letter: for example Espanol instead of espanol. 
- [x] If you go to the homepage and select Korean in languages and then click on the menu and select Tutorials, the Tutorials page will be displayed in English, not in Korean. Expectation would be for the selected language to be maintained when navigating through the site.

**Comment by stalgiag** [comment]
I can't recreate the second one. Are you able to reproduce a second time? Are you clicking the tutorials link in the sidebar?

**Comment by ccanash** [comment]
Re tested after fix and the second item has been resolved

**Comment by stalgiag** [comment]
Both done. Closing for now but can be reopened if others are found
