### ISSUE TITLE
GitLocalize translations of examples don't build without extra files

### ISSUE THREAD

**Issue by davepagurek** [bocoup/p5.js-website#58]
@limzykenneth https://github.com/bocoup/p5.js-website/pull/56 currently is failing because it places only the .mdx file of the example into the `es` folder. The `en` folder has an mdx as well as a `code.js` file.

[It doesn't look like GitLocalize supports translating .js files](https://docs.gitlocalize.com/file_formats.html), in case we wanted to translate comments.

If we don't care about the js file, we can maybe adapt the script that fetches the code for an example so that it always fetches the `en` version: https://github.com/bocoup/p5.js-website/blob/6e32d9150fdd9b37240ddf8f69692fc87f5967a4/src/pages/examples/%5B...slug%5D.astro#L15

**Comment by limzykenneth** [comment]
We don't need to translate the JS files for now so it can be that for files that are missing they get copied over from the English version, similar to how it should be working for missing translations.
