### ISSUE TITLE
Reference file name clash

### ISSUE THREAD

**Issue by limzykenneth** [bocoup/p5.js-website#68]
It is an edge case that needs to be deal with but essentially the translators noticed that when trying to translate `smooth()` the file it is pointing to is actually the [reference](https://github.com/bocoup/p5.js-website/blob/main/src/content/reference/en/p5/smooth.mdx) for the constant `SMOOTH` instead. The reference for `smooth()` is presumably overwritten.

The current website handles it with the capitalization difference but with file based routing here, is there some way to handle both `smooth()` and `SMOOTH` given some file system can't handle case sensitivity?

**Comment by limzykenneth** [comment]
@stalgiag @outofambit

**Comment by stalgiag** [comment]
Thanks for catching this! We can look at putting all of the global consts into a separate directory. I may not be able to get to this till next week. Would this be a major disruption to the localization process?

**Comment by limzykenneth** [comment]
@stalgiag It is blocking some of those entries from being translated as we are translating functions and not constants at the moment. Not a big problem for now though as we still have other entries to translate anyway so next week is fine.
