### ISSUE TITLE
Setting to run checks

### ISSUE THREAD

**Issue by Qianqianye** [bocoup/p5.js-website#91]
Hi @stalgiag @outofambit,

I can't merge the translation PRs because most of the latest PRs won't run the check, like #78. Is there a setting you can update to allow the PRs from other contributors to run checks? Or can you update my permission to run the checks? Thanks!

CC @limzykenneth @davepagurek

**Comment by stalgiag** [comment]
I made sure that all of you are admins. Not sure why those tests still are not running. The settings allow for workflows to happen for PRs from new contributors. Since they are just translations, you can bypass the status check if needed for unblocking

**Comment by limzykenneth** [comment]
Ideally it would be good to have the tests run and passed as there could be formatting issues. I'm also not able to merge it bypassing the checks and the only option is "Enable auto-merge", there's also no option currently to start the workflow run though, not sure why as it is not indicating that it requires permission or something.

**Comment by davepagurek** [comment]
Just a heads up, I had to fix some build errors (https://github.com/bocoup/p5.js-website/pull/109) from indentation and little minor things that are hard to check by skimming a PR manually.

**Comment by outofambit** [comment]
hi all! i realized the issue was that our CI workflows didn't support PRs from forks. i fixed this in #114 and updated all the open PRs to have this change. if anyone opens a PR from a fork and has this issue, updating the PR from main should get it unstuck. thanks!

**Comment by davepagurek** [comment]
awesome, thanks @outofambit!
